version: '3'
services:
  rest-service:
    build: .
    ports: 
      - '3000:3000'
    depends_on:
      - mongo
      - react-client
    environment:
      DATABASE_URL: 'mongodb://monty:pass@mongo:27017/mydatabase?authSource=admin&directConnection=true'
  mongo:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports: 
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: monty
      MONGO_INITDB_ROOT_PASSWORD: pass
  react-client:
    build: ../client
    ports:
      - '8000:8000'